import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Providers from "@/utility/providers";

const vazir = Vazirmatn({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  authors: [
    {
      name: "Maysam Ghaysari",
      url: "https://portfolio-me-one-amber.vercel.app",
    },
  ],

  title: "booking",
  description: "Generated by create next app and typescript",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body className={`${vazir.variable} antialiased  `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
